New-ADUser -Name "Ronald Mavarez" -GivenName "Ronald" -Surname "Mavarez" -SamAccountName "ronald" -UserPrincipalName "ronald@contoso.internal" -Path "OU=SharePoint,DC=contoso,DC=internal" -AccountPassword(Read-Host -AsSecureString "Provide Password") -Enabled $true
New-ADUser -Name "Esther Villalobos" -GivenName "Esther" -Surname "Villalobos" -SamAccountName "Esther" -UserPrincipalName "Esther@contoso.internal" -Path "OU=SharePoint,DC=contoso,DC=internal" -AccountPassword(Read-Host -AsSecureString "Provide Password") -Enabled $true
New-ADUser -Name "Rony Mavarez" -GivenName "Rony" -Surname "Mavarez" -SamAccountName "Rony" -UserPrincipalName "Rony@contoso.internal" -Path "OU=SharePoint,DC=contoso,DC=internal" -AccountPassword(Read-Host -AsSecureString "Provide Password") -Enabled $true
New-ADUser -Name "Randy Mavarez" -GivenName "Randy" -Surname "Mavarez" -SamAccountName "Randy" -UserPrincipalName "Randy@contoso.internal" -Path "OU=SharePoint,DC=contoso,DC=internal" -AccountPassword(Read-Host -AsSecureString "Provide Password") -Enabled $true
New-ADUser -Name "Reimy Mavarez" -GivenName "Reimy" -Surname "Mavarez" -SamAccountName "Reimy" -UserPrincipalName "Reimy@contoso.internal" -Path "OU=SharePoint,DC=contoso,DC=internal" -AccountPassword(Read-Host -AsSecureString "Provide Password") -Enabled $true
New-ADUser -Name "Isabel Mavarez" -GivenName "Isabel" -Surname "Mavarez" -SamAccountName "Isabel" -UserPrincipalName "Isabel@contoso.internal" -Path "OU=SharePoint,DC=contoso,DC=internal" -AccountPassword(Read-Host -AsSecureString "Provide Password") -Enabled $true
New-ADUser -Name "Ricardo Mavarez" -GivenName "Ricardo" -Surname "Mavarez" -SamAccountName "Ricardo" -UserPrincipalName "Ricardo@contoso.internal" -Path "OU=SharePoint,DC=contoso,DC=internal" -AccountPassword(Read-Host -AsSecureString "Provide Password") -Enabled $true
New-ADUser -Name "Mia Mavarez" -GivenName "Mia" -Surname "Mavarez" -SamAccountName "Mia" -UserPrincipalName "Mia@contoso.internal" -Path "OU=SharePoint,DC=contoso,DC=internal" -AccountPassword(Read-Host -AsSecureString "Provide Password") -Enabled $true
New-ADUser -Name "Pedro Mavarez" -GivenName "Pedro" -Surname "Mavarez" -SamAccountName "Pedro" -UserPrincipalName "Pedro@contoso.internal" -Path "OU=SharePoint,DC=contoso,DC=internal" -AccountPassword(Read-Host -AsSecureString "Provide Password") -Enabled $true
New-ADUser -Name "Reina Rodriguez" -GivenName "Reina" -Surname "Rodriguez" -SamAccountName "reina" -UserPrincipalName "Reina@contoso.internal" -Path "OU=SharePoint,DC=contoso,DC=internal" -AccountPassword(Read-Host -AsSecureString "Provide Password") -Enabled $true

#SharePoint Accounts
New-ADUser -Name "SP_Farm" -GivenName "SP_Farm" -Surname "SP_Farm" -SamAccountName "SP_Farm" -UserPrincipalName "SP_Farm@contoso.internal" -Path "OU=ServiceAccounts,DC=contoso,DC=internal" -AccountPassword(Read-Host -AsSecureString "Provide Password") -Enabled $true
New-ADUser -Name "SP_Services" -GivenName "SP_Services" -Surname "SP_Services" -SamAccountName "SP_Services" -UserPrincipalName "SP_Services@contoso.internal" -Path "OU=ServiceAccounts,DC=contoso,DC=internal" -AccountPassword(Read-Host -AsSecureString "Provide Password") -Enabled $true
New-ADUser -Name "SP_PortalAppPool" -GivenName "SP_PortalAppPool" -Surname "SP_PortalAppPool" -SamAccountName "SP_PortalAppPool" -UserPrincipalName "SP_PortalAppPool@contoso.internal" -Path "OU=ServiceAccounts,DC=contoso,DC=internal" -AccountPassword(Read-Host -AsSecureString "Provide Password") -Enabled $true
New-ADUser -Name "SP_ProfilesAppPool" -GivenName "SP_ProfilesAppPool" -Surname "SP_ProfilesAppPool" -SamAccountName "SP_ProfilesAppPool" -UserPrincipalName "SP_ProfilesAppPool@contoso.internal" -Path "OU=ServiceAccounts,DC=contoso,DC=internal" -AccountPassword(Read-Host -AsSecureString "Provide Password") -Enabled $true
New-ADUser -Name "SP_SearchService" -GivenName "SP_SearchService" -Surname "SP_SearchService" -SamAccountName "SP_SearchService" -UserPrincipalName "SP_SearchService@contoso.internal" -Path "OU=ServiceAccounts,DC=contoso,DC=internal" -AccountPassword(Read-Host -AsSecureString "Provide Password") -Enabled $true
New-ADUser -Name "SP_CacheSuperUser" -GivenName "SP_CacheSuperUser" -Surname "SP_CacheSuperUser" -SamAccountName "SP_CacheSuperUser" -UserPrincipalName "SP_CacheSuperUser@contoso.internal" -Path "OU=ServiceAccounts,DC=contoso,DC=internal" -AccountPassword(Read-Host -AsSecureString "Provide Password") -Enabled $true
New-ADUser -Name "SP_CacheSuperReader" -GivenName "SP_CacheSuperReader" -Surname "SP_CacheSuperReader" -SamAccountName "SP_CacheSuperReader" -UserPrincipalName "SP_CacheSuperReader@contoso.internal" -Path "OU=ServiceAccounts,DC=contoso,DC=internal" -AccountPassword(Read-Host -AsSecureString "Provide Password") -Enabled $true
New-ADUser -Name "SP_SearchContent" -GivenName "SP_SearchContent" -Surname "SP_SearchContent" -SamAccountName "SP_SearchContent" -UserPrincipalName "SP_SearchContent@contoso.internal" -Path "OU=ServiceAccounts,DC=contoso,DC=internal" -AccountPassword(Read-Host -AsSecureString "Provide Password") -Enabled $true
New-ADUser -Name "SP_ProfileSync" -GivenName "SP_ProfileSync" -Surname "SP_ProfileSync" -SamAccountName "SP_ProfileSync" -UserPrincipalName "SP_ProfileSync@contoso.internal" -Path "OU=ServiceAccounts,DC=contoso,DC=internal" -AccountPassword(Read-Host -AsSecureString "Provide Password") -Enabled $true
New-ADUser -Name "SP_ExcelUser" -GivenName "SP_ExcelUser" -Surname "SP_ExcelUser" -SamAccountName "SP_ExcelUser" -UserPrincipalName "SP_ExcelUser@contoso.internal" -Path "OU=ServiceAccounts,DC=contoso,DC=internal" -AccountPassword(Read-Host -AsSecureString "Provide Password") -Enabled $true
New-ADUser -Name "SP_VisioUser" -GivenName "SP_VisioUser" -Surname "SP_VisioUser" -SamAccountName "SP_VisioUser" -UserPrincipalName "SP_VisioUser@contoso.internal" -Path "OU=ServiceAccounts,DC=contoso,DC=internal" -AccountPassword(Read-Host -AsSecureString "Provide Password") -Enabled $true
New-ADUser -Name "SP_PerfPointUser" -GivenName "SP_PerfPointUser" -Surname "SP_PerfPointUser" -SamAccountName "SP_PerfPointUser" -UserPrincipalName "SP_PerfPointUser@contoso.internal" -Path "OU=ServiceAccounts,DC=contoso,DC=internal" -AccountPassword(Read-Host -AsSecureString "Provide Password") -Enabled $true
New-ADUser -Name "SP_ProjectServer" -GivenName "SP_ProjectServer" -Surname "SP_ProjectServer" -SamAccountName "SP_ProjectServer" -UserPrincipalName "SP_ProjectServer@contoso.internal" -Path "OU=ServiceAccounts,DC=contoso,DC=internal" -AccountPassword(Read-Host -AsSecureString "Provide Password") -Enabled $true